### ISSUE TITLE
💡 [INTERNAL] - Add GitHub Actions & App

### ISSUE THREAD

**Issue by Mittelblut9** [Mittelbots/Mittelbot#1455]
### Drawbacks

More improvments for pull requests, issues and releases

```[tasklist]
### Tasks
- [x] https://github.com/marketplace/actions/first-interaction
- [x] https://github.com/marketplace/actions/release-drafter
- [x] https://github.com/marketplace/pull-request-checklist-buddy
- [x] https://github.com/marketplace/pull-request-size/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNjcy
- [x] https://github.com/marketplace/create-issue-branch/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4zMDY5
```

**Comment by Mittelblut9** [comment]
Done
